/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pTuj1P5Aifw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="mx-auto max-w-md space-y-6 px-4 py-12 border border-gray-200 rounded-lg shadow-lg dark:border-gray-800">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Upload a File</h1>
        <p className="text-gray-500 dark:text-gray-400">Add a new file to your account.</p>
      </div>
      <form className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="file-name">File Name</Label>
          <Input id="file-name" placeholder="Enter a file name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="file-description">File Description</Label>
          <Textarea className="min-h-[100px]" id="file-description" placeholder="Describe your file" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="file">File</Label>
          <Input id="file" required type="file" />
        </div>
        <Button className="w-full" type="submit">
          Upload
        </Button>
      </form>
    </div>
  )
}
